name: Node.js versions

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        node: [ 16 ]
        include:
          - os: windows-latest
            redis_user: ''
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Show configuration
        run: |
          npm config get user-agent
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci
      - uses: ./action
      - name: Run e2e tests
        run: npm run test:e2e